# Generated by Django 5.1.2 on 2024-11-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('intro', models.CharField(max_length=250)),
                ('full_text', models.TextField()),
            ],
        ),
    ]
